In [85]:
import os
import pandas as pd
import utils

drug_combination_df = pd.read_csv(os.path.join('data/DrugCombDB', 'drug_combinations.csv'))
k = 5
bucket_size = len(drug_combination_df) // k
buckets_space = [bucket_size // k] * 5
buckets = [[] for _ in range(k)]
print(len(drug_combination_df))
drug_combination_df

69436

,Drug1,Drug2,cell,drug1_db,drug2_db,synergy
0,5-FU,BORTEZOMIB,A2058,DB00544,DB00188,-2.3950
1,5-FU,DASATINIB,A2058,DB00544,DB01254,1.5075
2,5-FU,ERLOTINIB,A2058,DB00544,DB00530,8.2525
3,5-FU,GELDANAMYCIN,A2058,DB00544,DB02424,6.0575
4,5-FU,LAPATINIB,A2058,DB00544,DB01259,4.9200
...,...,...,...,...,...,...
69431,Sunitinib malate,Toremifene citrate,HUH7,DB01268,DB00539,1.7320
69432,Sunitinib malate,Aripiprazole,HUH7,DB01268,DB01238,-6.5290
69433,Toremifene citrate,Toremifene citrate,HUH7,DB00539,DB00539,-6.3900
69434,Toremifene citrate,Aripiprazole,HUH7,DB00539,DB01238,-5.5540
69435,Aripiprazole,Aripiprazole,HUH7,DB01238,DB01238,-3.3700

In [89]:
from utils import create_folds
folds = create_folds(drug_combination_df,5,['Drug1', 'Drug2'])

NameError: name 'r' is not defined

### Create dataframe with indices and count

In [ ]:
grouped_df = drug_combination_df.groupby(['Drug1', 'Drug2'])
result_data = []
for (col1, col2), group in grouped_df:
    indices = group.index.tolist()
    count = len(indices)
    result_data.append([col1, col2, indices, count])

# Create a new DataFrame from the collected data
result_df = pd.DataFrame(result_data, columns=['Drug1', 'Drug2', 'indices', 'count'])

result_df = result_df.sort_values(by='count', ascending=False).reset_index(drop=True)

In [ ]:

result_df

,Drug1,Drug2,indices,count
0,5-FU,SORAFENIB,"[5, 103, 201, 299, 397, 495, 593, 691, 789, 88...",65
1,5-FU,BORTEZOMIB,"[0, 98, 196, 294, 392, 490, 588, 686, 784, 882...",65
2,5-FU,SUNITINIB,"[6, 104, 202, 300, 398, 496, 594, 692, 790, 88...",65
3,5-FU,DASATINIB,"[1, 99, 197, 295, 393, 491, 589, 687, 785, 883...",65
4,SUNITINIB,SORAFENIB,"[81, 179, 277, 375, 473, 571, 669, 767, 865, 9...",64
...,...,...,...,...
2457,LORNOXICAM,RUXOLITINIB,[68730],1
2458,LOVASTATIN,RUXOLITINIB,[68853],1
2459,LY-294002,Ruxolitinib,[69278],1
2460,Levonorgestrel,Ruxolitinib,[69373],1
2461,xylometazoline,RUXOLITINIB,[68934],1

### Put these into buckets

In [ ]:
for index, row in result_df.iterrows():
    bucket_index = r.randint(0,k-1)
    # check if bucket has enough space
    if buckets_space[bucket_index] < row.iloc[3]:
        checked = 1
        while checked < k:
            if bucket_index == k-1:
                bucket_index = 0
            else:
                bucket_index += 1
            if buckets_space[bucket_index] > row.iloc[3]:
                break
            checked += 1
    buckets[bucket_index] += row.iloc[2]
    buckets_space[bucket_index] = buckets_space[bucket_index] - row.iloc[3]

buckets[0]

[0,
 98,
 196,
 294,
 392,
 490,
 588,
 686,
 784,
 882,
 980,
 1078,
 1170,
 1268,
 1366,
 1464,
 1562,
 1659,
 1757,
 1855,
 1953,
 2051,
 2148,
 2246,
 2344,
 2442,
 2540,
 2638,
 2732,
 2830,
 2928,
 33525,
 33526,
 33527,
 33528,
 33529,
 33530,
 33531,
 33532,
 33533,
 33534,
 33535,
 33536,
 33537,
 33538,
 33539,
 33540,
 33541,
 33542,
 33543,
 33544,
 33545,
 33546,
 33547,
 33548,
 33549,
 33550,
 33551,
 33552,
 33553,
 33554,
 33555,
 33556,
 33557,
 33558,
 3771,
 5277,
 6032,
 6759,
 8065,
 8068,
 8602,
 9205,
 9468,
 10035,
 10202,
 11550,
 12270,
 12427,
 12559,
 12588,
 13088,
 13122,
 13502,
 14652,
 14978,
 15803,
 16595,
 16628,
 17532,
 17820,
 18793,
 18826,
 19236,
 19344,
 19715,
 20628,
 21967,
 22090,
 24000,
 24590,
 26224,
 26252,
 27595,
 30598,
 46096,
 46097,
 68762,
 47949,
 47950,
 47951,
 47952,
 47953,
 47954,
 47955,
 47956,
 47957,
 47958,
 47959,
 47960,
 47961,
 47962,
 47963,
 47964,
 47965,
 47966,
 47967,
 47968,
 47969,
 47970,
 47971,
 47972,
 47973,
 47974,
 47975,
 47976,
 47977,
 47978,
 47979,
 47980,
 47981,
 47982,
 47983,
 47984,
 47985,
 47986,
 47987,
 47988,
 47989,
 47990,
 58175,
 58176,
 58177,
 58178,
 58179,
 58180,
 58181,
 58182,
 58183,
 58184,
 58185,
 58186,
 58187,
 58188,
 58189,
 58190,
 58191,
 58192,
 58193,
 58194,
 58195,
 58196,
 58197,
 58198,
 58199,
 58200,
 58201,
 58202,
 58203,
 58204,
 58205,
 58206,
 58207,
 58208,
 58209,
 58210,
 58211,
 58212,
 58213,
 58214,
 58215,
 58216,
 60448,
 60449,
 60450,
 60451,
 60452,
 60453,
 60454,
 60455,
 60456,
 60457,
 60458,
 60459,
 60460,
 60461,
 60462,
 60463,
 60464,
 60465,
 60466,
 60467,
 60468,
 60469,
 60470,
 60471,
 60472,
 60473,
 60474,
 60475,
 60476,
 60477,
 60478,
 60479,
 60480,
 60481,
 60482,
 60483,
 60484,
 60485,
 60486,
 60487,
 60488,
 60489,
 65004,
 65005,
 65006,
 65007,
 65008,
 65009,
 65010,
 65011,
 65012,
 65013,
 65014,
 65015,
 65016,
 65017,
 65018,
 65019,
 65020,
 65021,
 65022,
 65023,
 65024,
 65025,
 65026,
 65027,
 65028,
 65029,
 65030,
 65031,
 65032,
 65033,
 65034,
 65035,
 65036,
 65037,
 65038,
 65039,
 65040,
 65041,
 65042,
 65043,
 65044,
 65045,
 40572,
 40573,
 40574,
 40575,
 40576,
 40577,
 40578,
 40579,
 40580,
 40581,
 40582,
 40583,
 40584,
 40585,
 40586,
 40587,
 40588,
 40589,
 40590,
 40591,
 40592,
 40593,
 40594,
 40595,
 40596,
 40597,
 40598,
 40599,
 40600,
 40601,
 40602,
 40603,
 40604,
 40605,
 40606,
 40607,
 40608,
 40609,
 40610,
 40611,
 40612,
 40613,
 46763,
 46764,
 46765,
 46766,
 46767,
 46768,
 46769,
 46770,
 46771,
 46772,
 46773,
 46774,
 46775,
 46776,
 46777,
 46778,
 46779,
 46780,
 46781,
 46782,
 46783,
 46784,
 46785,
 46786,
 46787,
 46788,
 46789,
 46790,
 46791,
 46792,
 46793,
 46794,
 46795,
 46796,
 46797,
 46798,
 46799,
 46800,
 46801,
 46802,
 46803,
 46804,
 41766,
 41767,
 41768,
 41769,
 41770,
 41771,
 41772,
 41773,
 41774,
 41775,
 41776,
 41777,
 41778,
 41779,
 41780,
 41781,
 41782,
 41783,
 41784,
 41785,
 41786,
 41787,
 41788,
 41789,
 41790,
 41791,
 41792,
 41793,
 41794,
 41795,
 41796,
 41797,
 41798,
 41799,
 41800,
 41801,
 41802,
 41803,
 41804,
 41805,
 41806,
 41807,
 53776,
 53777,
 53778,
 53779,
 53780,
 53781,
 53782,
 53783,
 53784,
 53785,
 53786,
 53787,
 53788,
 53789,
 53790,
 53791,
 53792,
 53793,
 53794,
 53795,
 53796,
 53797,
 53798,
 53799,
 53800,
 53801,
 53802,
 53803,
 53804,
 53805,
 53806,
 53807,
 53808,
 53809,
 53810,
 53811,
 53812,
 53813,
 53814,
 53815,
 53816,
 53817,
 54937,
 54938,
 54939,
 54940,
 54941,
 54942,
 54943,
 54944,
 54945,
 54946,
 54947,
 54948,
 54949,
 54950,
 54951,
 54952,
 54953,
 54954,
 54955,
 54956,
 54957,
 54958,
 54959,
 54960,
 54961,
 54962,
 54963,
 54964,
 54965,
 54966,
 54967,
 54968,
 54969,
 54970,
 54971,
 54972,
 54973,
 54974,
 54975,
 54976,
 54977,
 54978,
 68542,
 68543,
 68544,
 68545,
 68546,
 68547,
 68548,
 68549,
 68550,
 68551,
 68552,
 68553,
 68554,
 68555,
 68556,
 68557,
 68558,
 68559,
 68560,
 68561,
 68562,
 68563,
 68564,
 68565,
 68566,
 68567,
 68568,
 68569,
 68570,
 68571,
 68572,
 68573,
 68574,
 68575,
 68576,
 68577,
 68578,
 68579,
 68580,
 68581,
 68582,
 68583,
 36853,
 36854,
 36855,
 36856,
 36857,
 36858,
 36859,
 36860,
 36861,
 36862,
 36863,
 36864,
 36865,
 36866,
 36867,
 36868,
 36869,
 36870,
 36871,
 36872,
 36873,
 36874,
 36875,
 36876,
 36877,
 36878,
 36879,
 36880,
 36881,
 36882,
 36883,
 36884,
 36885,
 36886,
 36887,
 36888,
 36889,
 36890,
 36891,
 36892,
 36893,
 36894,
 39290,
 39291,
 39292,
 39293,
 39294,
 39295,
 39296,
 39297,
 39298,
 39299,
 39300,
 39301,
 39302,
 39303,
 39304,
 39305,
 39306,
 39307,
 39308,
 39309,
 39310,
 39311,
 39312,
 39313,
 39314,
 39315,
 39316,
 39317,
 39318,
 39319,
 39320,
 39321,
 39322,
 39323,
 39324,
 39325,
 39326,
 39327,
 39328,
 39329,
 39330,
 39331,
 3590,
 3624,
 3883,
 3915,
 5577,
 6068,
 6748,
 6962,
 8288,
 10894,
 11044,
 12047,
 13621,
 13882,
 14929,
 15165,
 15206,
 15270,
 15461,
 18334,
 18424,
 19839,
 20217,
 20579,
 21328,
 23350,
 24367,
 24421,
 25633,
 25707,
 25757,
 26792,
 26834,
 27297,
 27640,
 27801,
 29484,
 29740,
 30971,
 31161,
 31761,
 32356,
 56230,
 56231,
 56232,
 56233,
 56234,
 56235,
 56236,
 56237,
 56238,
 56239,
 56240,
 56241,
 56242,
 56243,
 56244,
 56245,
 56246,
 56247,
 56248,
 56249,
 56250,
 56251,
 56252,
 56253,
 56254,
 56255,
 56256,
 56257,
 56258,
 56259,
 56260,
 56261,
 56262,
 56263,
 56264,
 56265,
 56266,
 56267,
 56268,
 56269,
 56270,
 56271,
 50319,
 50320,
 50321,
 50322,
 50323,
 50324,
 50325,
 50326,
 50327,
 50328,
 50329,
 50330,
 50331,
 50332,
 50333,
 50334,
 50335,
 50336,
 50337,
 50338,
 50339,
 50340,
 50341,
 50342,
 50343,
 50344,
 50345,
 50346,
 50347,
 50348,
 50349,
 50350,
 50351,
 50352,
 50353,
 50354,
 50355,
 50356,
 50357,
 50358,
 50359,
 50360,
 64962,
 64963,
 64964,
 64965,
 64966,
 64967,
 64968,
 64969,
 64970,
 64971,
 64972,
 64973,
 64974,
 64975,
 64976,
 64977,
 64978,
 64979,
 64980,
 64981,
 64982,
 64983,
 64984,
 64985,
 64986,
 64987,
 64988,
 64989,
 64990,
 64991,
 64992,
 64993,
 64994,
 64995,
 64996,
 64997,
 64998,
 64999,
 65000,
 65001,
 65002,
 65003,
 3935,
 5064,
 5090,
 5425,
 6594,
 7218,
 7698,
 8863,
 9200,
 9338,
 10755,
 11444,
 11573,
 11749,
 14888,
 15885,
 16103,
 16872,
 18404,
 18751,
 18817,
 18951,
 19813,
 20734,
 22127,
 23138,
 23511,
 23813,
 24604,
 26288,
 26884,
 27833,
 28974,
 30221,
 30655,
 30804,
 30903,
 31124,
 31247,
 31821,
 32301,
 65338,
 3408,
 3483,
 3620,
 3786,
 4706,
 4847,
 5266,
 5418,
 5496,
 5691,
 5977,
 6653,
 6854,
 7942,
 11874,
 13035,
 13574,
 14366,
 14814,
 14822,
 15791,
 16250,
 16468,
 16490,
 16512,
 16749,
 17742,
 18582,
 18814,
 18864,
 19558,
 21603,
 24944,
 25956,
 27421,
 28381,
 29136,
 29677,
 29930,
 30150,
 31915,
 32458,
 3039,
 4087,
 4307,
 4565,
 6182,
 8657,
 9630,
 11320,
 11432,
 11503,
 12530,
 13597,
 13701,
 14135,
 14286,
 15118,
 15531,
 15837,
 16784,
 17162,
 18760,
 19187,
 20439,
 20755,
 22544,
 22764,
 22860,
 23167,
 23461,
 23477,
 23639,
 24066,
 25608,
 26755,
 26905,
 28601,
 29760,
 30014,
 30040,
 30106,
 30606,
 32399,
 3269,
 4066,
 4195,
 6407,
 7110,
 7613,
 8151,
 8180,
 8213,
 9616,
 11341,
 11742,
 16061,
 16711,
 16741,
 17443,
 17474,
 17968,
 18316,
 18800,
 19411,
 19435,
 19602,
 20511,
 21333,
 21747,
 22339,
 22683,
 23226,
 23485,
 23795,
 24116,
 24170,
 25950,
 26118,
 26517,
 27778,
 30079,
 30476,
 30688,
 31108,
 32022,
 3573,
 5485,
 6275,
 6965,
 7570,
 9731,
 10240,
 10663,
 11155,
 11458,
 11557,
 12247,
 12292,
 13665,
 15385,
 16524,
 16927,
 17276,
 18247,
 18607,
 19605,
 20119,
 21321,
 21582,
 21788,
 22187,
 22423,
 22938,
 24092,
 24147,
 24204,
 24679,
 24705,
 26874,
 27360,
 28297,
 28362,
 28969,
 30477,
 31950,
 32371,
 32549,
 54482,
 54483,
 54484,
 54485,
 54486,
 54487,
 54488,
 54489,
 54490,
 54491,
 ...]

In [ ]:
total_count = 0
for bucket in buckets:
    total_count += len(bucket)
total_count

69436